# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FiMap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire-SwiftyJSON' , '~> 3.0.0'
  pod 'R.swift'              , '~> 4.0.0'
  pod 'Kingfisher'           , '~> 4.8.0'
  pod 'SideMenu'             , '~> 4.0.0'
  pod 'SnapKit'              , '~> 4.0.0'
  # Pods for FiMap

end
